version: '3.7'
services:
 lets_encrypt:
    build: .
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt:/mnt
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /var/log/docker_log:/var/log/docker_log
    image: lets_encrypt
    container_name: lets_encrypt 
