version: '3.7'
services:
 lets_encrypt:
    build: .
    ports:
      - "80:80"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /var/log/docker_log/lets_encrypt:/var/log/docker_log
    image: lets_encrypt
    container_name: lets_encrypt
networks:
  default:
    external:
      name: default_bridge
